package Analizador;

public enum Type {
    OPEN_CURLY_BRACES, CLOSE_CURLY_BRACES, DOUBLE_PERCENTAGE, ARROW, COMMA, COLON, SEMI_COLON, STRING, ID, ERROR, MACRO, CONJ, UNDEFINED, COMMENT,
    DOT, OR, QUESTION_MARK, TIMES, PLUS, EOF

}
